### ISSUE TITLE
karma-tap 4.0.0 does not work in IE11

### ISSUE THREAD

**Issue by henry-luo** [bySabi/karma-tap#28]
I just tried out karma-tap 4.0.0, and found that it failed to run in IE11. After some troubleshooting, I found that the problem is due to its dependency tap-parser, which used new ES6 features in the code.

As karma-tap 4.0.0 switched to latest tap-parser 7.0.0, which uses ES6 features, it no longer runs in legacy browsers, like IE11, which has limited ES6 support.

If karma-tap is not going to support legacy browsers (like IE11) onward, then it probably should document it in it README file, and advise people to use previous versions of karma-tap, like 3.1.1, which runs properly in IE11.

**Comment by bySabi** [comment]
I don't tested my self on IE11 but maybe with can add support to IE11 with some polyfill. 
Could you provide some failed output?

**Comment by bySabi** [comment]
never mine @henry-luo. I will transform `tap-parser` to ES5 before publish it

**Comment by henry-luo** [comment]
IE11 does not support class. But latest tap-parser makes extensive use of ES6 class.

So to transform to ES5 is a possible solution. The other way is to just use karma-tap 3.1.1 for IE11.

I can help do a test in IE11 when you are done.

**Comment by bySabi** [comment]
I think is solved on new release, 4.1.0. Please upgrade.

Reopen the issue is something goes wrong.

**Comment by henry-luo** [comment]
I tested the latest version. It still does NOT work in IE11, the error is below:
> IE 11.0.0 (Windows 10 0.0.0) ERROR
  {
    "message": "Syntax error\nat node_modules/karma-tap/lib/parser.js:6639:1",
    "str": "Syntax error\nat node_modules/karma-tap/lib/parser.js:6639:1"
  }
IE 11.0.0 (Windows 10 0.0.0) ERROR
  {
    "message": "'tapParser' is undefined\nat node_modules/karma-tap/src/adapter.js:3:3\n\nReferenceError: 'tapParser' is undefined\n   at createStartFn (node_modules/karma-tap/src/adapter.js:3:3)\n   at Global code (node_modules/karma-tap/src/adapter.js:71:1)",
    "str": "'tapParser' is undefined\nat node_modules/karma-tap/src/adapter.js:3:3\n\nReferenceError: 'tapParser' is undefined\n   at createStartFn (node_modules/karma-tap/src/adapter.js:3:3)\n   at Global code (node_modules/karma-tap/src/adapter.js:71:1)"
  }

I checked and found that the classes in tap-parser are not transpiled at all. That's because browserify by default does not transform the dependencies. So I added global transform to babelify 
`-t [ babelify --presets [ env ] --global ]`

And now I encounter a different problem, as captured below:
> IE 11.0.0 (Windows 10 0.0.0) ERROR
  {
    "message": "'Symbol' is undefined\nat node_modules/karma-tap/lib/parser.js:6380:1\n\nReferenceError: 'Symbol' is undefined\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:6380:1)\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:6365:2)\n   at s (node_modules/karma-tap/lib/parser.js:1:615)\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:1:667)\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:7632:1)\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:7618:2)\n   at s (node_modules/karma-tap/lib/parser.js:1:615)\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:1:667)\n   at Anonymous function (node_modules/karma-tap/lib/parser.js:9136:1)\n   at s (node_modules/karma-tap/lib/parser.js:1:615)",

It seems Symbol polyfill is missing. So I added babel-plugin-transform-runtime, but still encounter other problem.

Now it is beyond my capability. And I simply cannot get it properly transpiled.

**Comment by bySabi** [comment]
Thanks for the feedback 👍 

I remove babel transformation stage on `karma-tap` 4.1.1 release , this will not work.
But new `3.2.0` release add `Karma 2` support and it's update to `tap-parser 5.4.0`.

Please test with release, 3.2.0. Branch 3.x.x will support ES5 browsers: https://github.com/bySabi/karma-tap/tree/3.X.X

**Comment by henry-luo** [comment]
Just tested, 3.2.0 has the problem as reported in issue #29.

And finally 3.2.1 has every thing fixed, and is working fine in IE11. 

Thanks for making it work for IE11! 🥇
